### ISSUE TITLE
Using missing=lazy throws error when missing interface doesn't use chain used by other interfaces

### ISSUE THREAD

**Issue by andybro19** [bearwall-firewall/bearwall2#27]
Using missing=lazy throws error when missing interface doesn't use chain used by other interfaces.

Version:  2.06

**Reproduction steps (example)**
1. Set `missing=lazy` in `/etc/bearwall2/bearwall2.conf`
2. Add line `policy postrouting accept` to `/etc/bearwall2/interfaces.d/<interface>.if`
3. Remove any `postrouting` policies from `/etc/bearwall2/interfaces.d/<missing>.if`
4. Run `sudo bearwall2`

**Result**
The new rule set is not applied and this is the output produced:

```
*** Configuring interfaces
 *  <interface>
 *  <missing>
    Interface '<missing>' is missing: using ifname due to lazy
*** Doing atomic load
 *  Invoking nftables (nft)
/var/cache/bearwall2/tmp/output.nftables:XX:3-3: Error: syntax error, unexpected '}'
		}
		^
```

**Expected Result**
The new rule set is applied with no errors.

**Comment by gizmoguy** [comment]
Does adding the following policy to your `<interface>.if` workaround the problem?

```
policy forward reject
```

**Comment by gizmoguy** [comment]
Nevermind, I think I see the problem. nftables doesn't like it when you give it an empty vmap.

**Comment by andybro19** [comment]
It just throws more errors. It looks like it's due to creating empty `meta oifname vmap {}` in `/var/cache/bearwall2/tmp/output.nftables`. Just noticed you just said that though.

**Comment by gizmoguy** [comment]
I initially couldn't replicate it on my machine with lots of interfaces, but taking it back to your repro case helped me clearly see the problem.

**Comment by gizmoguy** [comment]
I think I've fixed this now, here is a deb you can install locally to try the fix:

[bearwall2_2.06-1e1c26e1_all.deb.gz](https://github.com/bearwall-firewall/bearwall2/files/4796430/bearwall2_2.06-1e1c26e1_all.deb.gz)
